version: '3.8'
services:

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./backend/sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: capstonedb

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - my_network
    volumes:
      - ./backend:/app
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@host.docker.internal:5432/capstonedb
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db: 
    driver: local

networks:
  my_network:
      driver: bridge