/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('listings').del()
  await knex('listings').insert([
    {listingId: 1, user_id: 1, boat_id: 1},
    {listingId: 2, user_id: 2, boat_id: 2},
    {listingId: 3, user_id: 3, boat_id: 3},
    {listingId: 4, user_id: 4, boat_id: 4},
    {listingId: 5, user_id: 5, boat_id: 5},
    {listingId: 6, user_id: 6, boat_id: 6},
    {listingId: 7, user_id: 7, boat_id: 7},
    {listingId: 8, user_id: 8, boat_id: 8},
    {listingId: 9, user_id: 9, boat_id: 9},
    {listingId: 10, user_id: 10, boat_id: 10},
    {listingId: 11, user_id: 11, boat_id: 11},
    {listingId: 12, user_id: 12, boat_id: 12},
    {listingId: 13, user_id: 13, boat_id: 13},
    {listingId: 14, user_id: 14, boat_id: 14},
    {listingId: 15, user_id: 15, boat_id: 15},
    {listingId: 16, user_id: 16, boat_id: 16},
    {listingId: 17, user_id: 17, boat_id: 17},
    {listingId: 18, user_id: 18, boat_id: 18},
    {listingId: 19, user_id: 19, boat_id: 19},
    {listingId: 20, user_id: 20, boat_id: 20},
  
    {listingId: 21, user_id: 1, rv_id: 1},
    {listingId: 22, user_id: 2, rv_id: 2},
    {listingId: 23, user_id: 3, rv_id: 3},
    {listingId: 24, user_id: 4, rv_id: 4},
    {listingId: 25, user_id: 5, rv_id: 5},
    {listingId: 26, user_id: 6, rv_id: 6},
    {listingId: 27, user_id: 7, rv_id: 7},
    {listingId: 28, user_id: 8, rv_id: 8},
    {listingId: 29, user_id: 9, rv_id: 9},
    {listingId: 30, user_id: 10, rv_id: 10},
    {listingId: 31, user_id: 11, rv_id: 11},
    {listingId: 32, user_id: 12, rv_id: 12},
    {listingId: 33, user_id: 13, rv_id: 13},
    {listingId: 34, user_id: 14, rv_id: 14},
    {listingId: 35, user_id: 15, rv_id: 15},
    {listingId: 36, user_id: 16, rv_id: 16},
    {listingId: 37, user_id: 17, rv_id: 17},
    {listingId: 38, user_id: 18, rv_id: 18},
    {listingId: 39, user_id: 19, rv_id: 19},
    {listingId: 40, user_id: 20, rv_id: 20},
  
    {listingId: 41, user_id: 1, trailer_id: 1},
    {listingId: 42, user_id: 2, trailer_id: 2},
    {listingId: 43, user_id: 3, trailer_id: 3},
    {listingId: 44, user_id: 4, trailer_id: 4},
    {listingId: 45, user_id: 5, trailer_id: 5},
    {listingId: 46, user_id: 6, trailer_id: 6},
    {listingId: 47, user_id: 7, trailer_id: 7},
    {listingId: 48, user_id: 8, trailer_id: 8},
    {listingId: 49, user_id: 9, trailer_id: 9},
    {listingId: 50, user_id: 10, trailer_id: 10},
    {listingId: 51, user_id: 11, trailer_id: 11},
    {listingId: 52, user_id: 12, trailer_id: 12},
    {listingId: 53, user_id: 13, trailer_id: 13},
    {listingId: 54, user_id: 14, trailer_id: 14},
    {listingId: 55, user_id: 15, trailer_id: 15},
    {listingId: 56, user_id: 16, trailer_id: 16},
    {listingId: 57, user_id: 17, trailer_id: 17},
    {listingId: 58, user_id: 18, trailer_id: 18},
    {listingId: 59, user_id: 19, trailer_id: 19},
    {listingId: 60, user_id: 20, trailer_id: 20},
  
    {listingId: 61, user_id: 1, car_id: 1},
    {listingId: 62, user_id: 2, car_id: 2},
    {listingId: 63, user_id: 3, car_id: 3},
    {listingId: 64, user_id: 4, car_id: 4},
    {listingId: 65, user_id: 5, car_id: 5},
    {listingId: 66, user_id: 6, car_id: 6},
    {listingId: 67, user_id: 7, car_id: 7},
    {listingId: 68, user_id: 8, car_id: 8},
    {listingId: 69, user_id: 9, car_id: 9},
    {listingId: 70, user_id: 10, car_id: 10},
    {listingId: 71, user_id: 11, car_id: 11},
    {listingId: 72, user_id: 12, car_id: 12},
    {listingId: 73, user_id: 13, car_id: 13},
    {listingId: 74, user_id: 14, car_id: 14},
    {listingId: 75, user_id: 15, car_id: 15},
    {listingId: 76, user_id: 16, car_id: 16},
    {listingId: 77, user_id: 17, car_id: 17},
    {listingId: 78, user_id: 18, car_id: 18},
    {listingId: 79, user_id: 19, car_id: 19},
    {listingId: 80, user_id: 20, car_id: 20},
  
    {listingId: 81, user_id: 1, motorcycle_id: 1},
    {listingId: 82, user_id: 2, motorcycle_id: 2},
    {listingId: 83, user_id: 3, motorcycle_id: 3},
    {listingId: 84, user_id: 4, motorcycle_id: 4},
    {listingId: 85, user_id: 5, motorcycle_id: 5},
    {listingId: 86, user_id: 6, motorcycle_id: 6},
    {listingId: 87, user_id: 7, motorcycle_id: 7},
    {listingId: 88, user_id: 8, motorcycle_id: 8},
    {listingId: 89, user_id: 9, motorcycle_id: 9},
    {listingId: 90, user_id: 10, motorcycle_id: 10},
    {listingId: 91, user_id: 11, motorcycle_id: 11},
    {listingId: 92, user_id: 12, motorcycle_id: 12},
    {listingId: 93, user_id: 13, motorcycle_id: 13},
    {listingId: 94, user_id: 14, motorcycle_id: 14},
    {listingId: 95, user_id: 15, motorcycle_id: 15},
    {listingId: 96, user_id: 16, motorcycle_id: 16},
    {listingId: 97, user_id: 17, motorcycle_id: 17},
    {listingId: 98, user_id: 18, motorcycle_id: 18},
    {listingId: 99, user_id: 19, motorcycle_id: 19},
    {listingId: 100, user_id: 20, motorcycle_id: 20}
    
  
  ]);
  // await knex.raw('SELECT setval(\'listings_listingId_seq\', (SELECT MAX(listingId) from "listings"));')
  await knex.raw("ALTER SEQUENCE \"listings_listingId_seq\" RESTART WITH 101;")
};
